version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 5555:3000
